# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default=None, max_length=10, null=True)),
                ('name', models.CharField(default=None, max_length=30, null=True)),
                ('headline', models.CharField(default=None, max_length=100, null=True)),
                ('abstract', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', stdimage.models.StdImageField(blank=True, upload_to=stdimage.utils.UploadToClassNameDirUUID())),
                ('tag', models.CharField(max_length=50)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('admin_only', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('content', models.ManyToManyField(default=None, to='py_monocle_cms.Content')),
            ],
        ),
    ]
