# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-29 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_monocle_cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='front_page',
            field=models.BooleanField(default=True),
        ),
    ]
