# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_monocle_cms', '0002_page_front_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='front_page',
            field=models.BooleanField(default=False),
        ),
    ]
