# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_monocle_cms', '0003_auto_20170731_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.AddField(
            model_name='page',
            name='abstract',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='body',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='headline',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
